
export const SET_ALERT='SET_ALERT';
export const REMOVE_ALERT='REMOVE_ALERT';
export const  REGISTER_SUCESS="REGISTER_SUCESS";
export const REGISTER_FAIL='REGISTER_FAIL';
export const USER_LOAD='USER_LOAD';
export const AUTH_ERR='AUTH_ERR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGOUT='LOGOUT';
export const GET_PROFILE='GET_PROFILE';
export const PROFILE_ERR='PROFILE_ERR';
export const UPDATE_PROFILE='UPDATE_PROFILE';
export const CLEAR_PROFILE='CLEAR_PROFILE';
